version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
        - my-db:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  my-db: